#!/bin/bash
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'
yl='\e[32;1m'
bl='\e[36;1m'
gl='\e[32;1m'
rd='\e[31;1m'
mg='\e[0;95m'
blu='\e[34m'
op='\e[35m'
or='\033[1;33m'
bd='\e[1m'
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'
clear
echo -e ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "\E[44;1;39m                  ⇱ SSH ⇲                      \E[0m"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"

echo -e "$yy 1$y.  Create SSH & OpenVPN Account"
echo -e "$yy 2$y.  Generate SSH & OpenVPN Trial Account"
echo -e "$yy 3$y.  Extending SSH & OpenVPN Account Active Life"
echo -e "$yy 4$y.  Check User Login SSH & OpenVPN"
echo -e "$yy 5$y.  Daftar Member SSH & OpenVPN"
echo -e "$yy 6$y.  Delete SSH & OpenVpn Account"
echo -e "$yy 7$y.  Delete User Expired SSH & OpenVPN"
echo -e "$yy 8$y.  Set up Autokill SSH"
echo -e "$yy 9$y.  Displays Users Who Do Multi Login SSH"
echo -e "$yy 10$y. Restart All Service"
echo -e "$yy 11$y. Menu Utama"
echo -e "$yy 12$y. Exit"

echo -e "❇️  1. Create Account"
echo -e "❇️  2. Delete Account"
echo -e "❇️  3. Extending Account"
echo -e "❇️  4. Check User Login"
echo -e "❇️  5. Autokill SSH"
echo -e "❇️  Enter to Menu"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "\E[44;1;39m                  ⇱ SSH ⇲                      \E[0m"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
read -p "     Select From Options [1-5 or x] :  " menu
case $menu in 
1)
add-ssh
;;
2)
del-ssh
;;
3)
ext-ssh
;;
4)
check-ssh
;;
5)
kill-ssh
;;
*)
clear
menu
;;
esac
