#!/bin/bash
# ==========================================
# download menu
cd /usr/bin
rm -rf menu
rm -rf setting
rm -rf updatemenu
rm -rf addvmess

wget -O unem "https://raw.githubusercontent.com/kuyaxxx/xray/main/unem/menu"
wget -O unem "https://raw.githubusercontent.com/kuyaxxx/xray/main/unem/setting"
wget -O unem "https://raw.githubusercontent.com/kuyaxxx/xray/main/unem/updatemenu"
wget -O unem "https://raw.githubusercontent.com/kuyaxxx/xray/main/unem/addvmess"

chmod +x menu
chmod +x setting
chmod +x updatemenu
chmod +x addvmess
cd ~
